name: allen-app
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - pandas
  - seaborn-base
  - ipykernel
  - jupyterlab
  - pip
  - python
  - pip:
      - streamlit
      - allensdk

